//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalogue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public int UserID { get; set; }
        public Nullable<int> SundayHrs { get; set; }
        public Nullable<int> MondayHrs { get; set; }
        public Nullable<int> TuesdayHrs { get; set; }
        public Nullable<int> WednesdayHrs { get; set; }
        public Nullable<int> ThursdayHrs { get; set; }
        public Nullable<int> FridayHrs { get; set; }
        public Nullable<int> SaturdayHrs { get; set; }
    
        public virtual User User { get; set; }
    }
}
